// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "github.com/stephenafamo/bob"

// Set the testDB to enable tests that use the database
var testDB bob.Transactor[bob.Tx]

// Make sure the type Invite runs hooks after queries
var _ bob.HookableType = &Invite{}

// Make sure the type Session runs hooks after queries
var _ bob.HookableType = &Session{}

// Make sure the type User runs hooks after queries
var _ bob.HookableType = &User{}
