// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// Invite is an object representing the database table.
type Invite struct {
	ID        int64               `db:"id,pk" `
	Code      string              `db:"code" `
	CreatedBy null.Val[int64]     `db:"created_by" `
	UsedBy    null.Val[int64]     `db:"used_by" `
	UsedAt    null.Val[time.Time] `db:"used_at" `
	ExpiresAt null.Val[time.Time] `db:"expires_at" `
	CreatedAt time.Time           `db:"created_at" `

	R inviteR `db:"-" `
}

// InviteSlice is an alias for a slice of pointers to Invite.
// This should almost always be used instead of []*Invite.
type InviteSlice []*Invite

// Invites contains methods to work with the invites table
var Invites = sqlite.NewTablex[*Invite, InviteSlice, *InviteSetter]("", "invites", buildInviteColumns("invites"))

// InvitesQuery is a query on the invites table
type InvitesQuery = *sqlite.ViewQuery[*Invite, InviteSlice]

// inviteR is where relationships are stored.
type inviteR struct {
	UsedByUser    *User // fk_invites_0
	CreatedByUser *User // fk_invites_1
}

func buildInviteColumns(alias string) inviteColumns {
	return inviteColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "code", "created_by", "used_by", "used_at", "expires_at", "created_at",
		).WithParent("invites"),
		tableAlias: alias,
		ID:         sqlite.Quote(alias, "id"),
		Code:       sqlite.Quote(alias, "code"),
		CreatedBy:  sqlite.Quote(alias, "created_by"),
		UsedBy:     sqlite.Quote(alias, "used_by"),
		UsedAt:     sqlite.Quote(alias, "used_at"),
		ExpiresAt:  sqlite.Quote(alias, "expires_at"),
		CreatedAt:  sqlite.Quote(alias, "created_at"),
	}
}

type inviteColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         sqlite.Expression
	Code       sqlite.Expression
	CreatedBy  sqlite.Expression
	UsedBy     sqlite.Expression
	UsedAt     sqlite.Expression
	ExpiresAt  sqlite.Expression
	CreatedAt  sqlite.Expression
}

func (c inviteColumns) Alias() string {
	return c.tableAlias
}

func (inviteColumns) AliasedAs(alias string) inviteColumns {
	return buildInviteColumns(alias)
}

// InviteSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type InviteSetter struct {
	ID        omit.Val[int64]         `db:"id,pk" `
	Code      omit.Val[string]        `db:"code" `
	CreatedBy omitnull.Val[int64]     `db:"created_by" `
	UsedBy    omitnull.Val[int64]     `db:"used_by" `
	UsedAt    omitnull.Val[time.Time] `db:"used_at" `
	ExpiresAt omitnull.Val[time.Time] `db:"expires_at" `
	CreatedAt omit.Val[time.Time]     `db:"created_at" `
}

func (s InviteSetter) SetColumns() []string {
	vals := make([]string, 0, 7)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Code.IsValue() {
		vals = append(vals, "code")
	}
	if !s.CreatedBy.IsUnset() {
		vals = append(vals, "created_by")
	}
	if !s.UsedBy.IsUnset() {
		vals = append(vals, "used_by")
	}
	if !s.UsedAt.IsUnset() {
		vals = append(vals, "used_at")
	}
	if !s.ExpiresAt.IsUnset() {
		vals = append(vals, "expires_at")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	return vals
}

func (s InviteSetter) Overwrite(t *Invite) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Code.IsValue() {
		t.Code = s.Code.MustGet()
	}
	if !s.CreatedBy.IsUnset() {
		t.CreatedBy = s.CreatedBy.MustGetNull()
	}
	if !s.UsedBy.IsUnset() {
		t.UsedBy = s.UsedBy.MustGetNull()
	}
	if !s.UsedAt.IsUnset() {
		t.UsedAt = s.UsedAt.MustGetNull()
	}
	if !s.ExpiresAt.IsUnset() {
		t.ExpiresAt = s.ExpiresAt.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
}

func (s *InviteSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Invites.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"id"}
		}

	}

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 0, 7)
		if s.ID.IsValue() {
			vals = append(vals, sqlite.Arg(s.ID.MustGet()))
		}

		if s.Code.IsValue() {
			vals = append(vals, sqlite.Arg(s.Code.MustGet()))
		}

		if !s.CreatedBy.IsUnset() {
			vals = append(vals, sqlite.Arg(s.CreatedBy.MustGetNull()))
		}

		if !s.UsedBy.IsUnset() {
			vals = append(vals, sqlite.Arg(s.UsedBy.MustGetNull()))
		}

		if !s.UsedAt.IsUnset() {
			vals = append(vals, sqlite.Arg(s.UsedAt.MustGetNull()))
		}

		if !s.ExpiresAt.IsUnset() {
			vals = append(vals, sqlite.Arg(s.ExpiresAt.MustGetNull()))
		}

		if s.CreatedAt.IsValue() {
			vals = append(vals, sqlite.Arg(s.CreatedAt.MustGet()))
		}

		if len(vals) == 0 {
			vals = append(vals, sqlite.Arg(nil))
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s InviteSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s InviteSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 7)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "id")...),
			sqlite.Arg(s.ID),
		}})
	}

	if s.Code.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "code")...),
			sqlite.Arg(s.Code),
		}})
	}

	if !s.CreatedBy.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "created_by")...),
			sqlite.Arg(s.CreatedBy),
		}})
	}

	if !s.UsedBy.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "used_by")...),
			sqlite.Arg(s.UsedBy),
		}})
	}

	if !s.UsedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "used_at")...),
			sqlite.Arg(s.UsedAt),
		}})
	}

	if !s.ExpiresAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "expires_at")...),
			sqlite.Arg(s.ExpiresAt),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "created_at")...),
			sqlite.Arg(s.CreatedAt),
		}})
	}

	return exprs
}

// FindInvite retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindInvite(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*Invite, error) {
	if len(cols) == 0 {
		return Invites.Query(
			sm.Where(Invites.Columns.ID.EQ(sqlite.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Invites.Query(
		sm.Where(Invites.Columns.ID.EQ(sqlite.Arg(IDPK))),
		sm.Columns(Invites.Columns.Only(cols...)),
	).One(ctx, exec)
}

// InviteExists checks the presence of a single record by primary key
func InviteExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return Invites.Query(
		sm.Where(Invites.Columns.ID.EQ(sqlite.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Invite is retrieved from the database
func (o *Invite) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Invites.AfterSelectHooks.RunHooks(ctx, exec, InviteSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Invites.AfterInsertHooks.RunHooks(ctx, exec, InviteSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Invites.AfterUpdateHooks.RunHooks(ctx, exec, InviteSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Invites.AfterDeleteHooks.RunHooks(ctx, exec, InviteSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Invite
func (o *Invite) primaryKeyVals() bob.Expression {
	return sqlite.Arg(o.ID)
}

func (o *Invite) pkEQ() dialect.Expression {
	return sqlite.Quote("invites", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Invite
func (o *Invite) Update(ctx context.Context, exec bob.Executor, s *InviteSetter) error {
	v, err := Invites.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Invite record with an executor
func (o *Invite) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Invites.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Invite using the executor
func (o *Invite) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Invites.Query(
		sm.Where(Invites.Columns.ID.EQ(sqlite.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after InviteSlice is retrieved from the database
func (o InviteSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Invites.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Invites.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Invites.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Invites.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o InviteSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Quote("invites", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o InviteSlice) copyMatchingRows(from ...*Invite) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o InviteSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Invites.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Invite:
				o.copyMatchingRows(retrieved)
			case []*Invite:
				o.copyMatchingRows(retrieved...)
			case InviteSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Invite or a slice of Invite
				// then run the AfterUpdateHooks on the slice
				_, err = Invites.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o InviteSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Invites.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Invite:
				o.copyMatchingRows(retrieved)
			case []*Invite:
				o.copyMatchingRows(retrieved...)
			case InviteSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Invite or a slice of Invite
				// then run the AfterDeleteHooks on the slice
				_, err = Invites.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o InviteSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals InviteSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Invites.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o InviteSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Invites.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o InviteSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Invites.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// UsedByUser starts a query for related objects on users
func (o *Invite) UsedByUser(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(sqlite.Arg(o.UsedBy))),
	)...)
}

func (os InviteSlice) UsedByUser(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.UsedBy)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return Users.Query(append(mods,
		sm.Where(sqlite.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// CreatedByUser starts a query for related objects on users
func (o *Invite) CreatedByUser(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(sqlite.Arg(o.CreatedBy))),
	)...)
}

func (os InviteSlice) CreatedByUser(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.CreatedBy)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return Users.Query(append(mods,
		sm.Where(sqlite.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachInviteUsedByUser0(ctx context.Context, exec bob.Executor, count int, invite0 *Invite, user1 *User) (*Invite, error) {
	setter := &InviteSetter{
		UsedBy: omitnull.From(user1.ID),
	}

	err := invite0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachInviteUsedByUser0: %w", err)
	}

	return invite0, nil
}

func (invite0 *Invite) InsertUsedByUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachInviteUsedByUser0(ctx, exec, 1, invite0, user1)
	if err != nil {
		return err
	}

	invite0.R.UsedByUser = user1

	user1.R.UsedByInvites = append(user1.R.UsedByInvites, invite0)

	return nil
}

func (invite0 *Invite) AttachUsedByUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachInviteUsedByUser0(ctx, exec, 1, invite0, user1)
	if err != nil {
		return err
	}

	invite0.R.UsedByUser = user1

	user1.R.UsedByInvites = append(user1.R.UsedByInvites, invite0)

	return nil
}

func attachInviteCreatedByUser0(ctx context.Context, exec bob.Executor, count int, invite0 *Invite, user1 *User) (*Invite, error) {
	setter := &InviteSetter{
		CreatedBy: omitnull.From(user1.ID),
	}

	err := invite0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachInviteCreatedByUser0: %w", err)
	}

	return invite0, nil
}

func (invite0 *Invite) InsertCreatedByUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachInviteCreatedByUser0(ctx, exec, 1, invite0, user1)
	if err != nil {
		return err
	}

	invite0.R.CreatedByUser = user1

	user1.R.CreatedByInvites = append(user1.R.CreatedByInvites, invite0)

	return nil
}

func (invite0 *Invite) AttachCreatedByUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachInviteCreatedByUser0(ctx, exec, 1, invite0, user1)
	if err != nil {
		return err
	}

	invite0.R.CreatedByUser = user1

	user1.R.CreatedByInvites = append(user1.R.CreatedByInvites, invite0)

	return nil
}

type inviteWhere[Q sqlite.Filterable] struct {
	ID        sqlite.WhereMod[Q, int64]
	Code      sqlite.WhereMod[Q, string]
	CreatedBy sqlite.WhereNullMod[Q, int64]
	UsedBy    sqlite.WhereNullMod[Q, int64]
	UsedAt    sqlite.WhereNullMod[Q, time.Time]
	ExpiresAt sqlite.WhereNullMod[Q, time.Time]
	CreatedAt sqlite.WhereMod[Q, time.Time]
}

func (inviteWhere[Q]) AliasedAs(alias string) inviteWhere[Q] {
	return buildInviteWhere[Q](buildInviteColumns(alias))
}

func buildInviteWhere[Q sqlite.Filterable](cols inviteColumns) inviteWhere[Q] {
	return inviteWhere[Q]{
		ID:        sqlite.Where[Q, int64](cols.ID),
		Code:      sqlite.Where[Q, string](cols.Code),
		CreatedBy: sqlite.WhereNull[Q, int64](cols.CreatedBy),
		UsedBy:    sqlite.WhereNull[Q, int64](cols.UsedBy),
		UsedAt:    sqlite.WhereNull[Q, time.Time](cols.UsedAt),
		ExpiresAt: sqlite.WhereNull[Q, time.Time](cols.ExpiresAt),
		CreatedAt: sqlite.Where[Q, time.Time](cols.CreatedAt),
	}
}

func (o *Invite) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "UsedByUser":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("invite cannot load %T as %q", retrieved, name)
		}

		o.R.UsedByUser = rel

		if rel != nil {
			rel.R.UsedByInvites = InviteSlice{o}
		}
		return nil
	case "CreatedByUser":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("invite cannot load %T as %q", retrieved, name)
		}

		o.R.CreatedByUser = rel

		if rel != nil {
			rel.R.CreatedByInvites = InviteSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("invite has no relationship %q", name)
	}
}

type invitePreloader struct {
	UsedByUser    func(...sqlite.PreloadOption) sqlite.Preloader
	CreatedByUser func(...sqlite.PreloadOption) sqlite.Preloader
}

func buildInvitePreloader() invitePreloader {
	return invitePreloader{
		UsedByUser: func(opts ...sqlite.PreloadOption) sqlite.Preloader {
			return sqlite.Preload[*User, UserSlice](sqlite.PreloadRel{
				Name: "UsedByUser",
				Sides: []sqlite.PreloadSide{
					{
						From:        Invites,
						To:          Users,
						FromColumns: []string{"used_by"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
		CreatedByUser: func(opts ...sqlite.PreloadOption) sqlite.Preloader {
			return sqlite.Preload[*User, UserSlice](sqlite.PreloadRel{
				Name: "CreatedByUser",
				Sides: []sqlite.PreloadSide{
					{
						From:        Invites,
						To:          Users,
						FromColumns: []string{"created_by"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type inviteThenLoader[Q orm.Loadable] struct {
	UsedByUser    func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	CreatedByUser func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildInviteThenLoader[Q orm.Loadable]() inviteThenLoader[Q] {
	type UsedByUserLoadInterface interface {
		LoadUsedByUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type CreatedByUserLoadInterface interface {
		LoadCreatedByUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return inviteThenLoader[Q]{
		UsedByUser: thenLoadBuilder[Q](
			"UsedByUser",
			func(ctx context.Context, exec bob.Executor, retrieved UsedByUserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUsedByUser(ctx, exec, mods...)
			},
		),
		CreatedByUser: thenLoadBuilder[Q](
			"CreatedByUser",
			func(ctx context.Context, exec bob.Executor, retrieved CreatedByUserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCreatedByUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadUsedByUser loads the invite's UsedByUser into the .R struct
func (o *Invite) LoadUsedByUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.UsedByUser = nil

	related, err := o.UsedByUser(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.UsedByInvites = InviteSlice{o}

	o.R.UsedByUser = related
	return nil
}

// LoadUsedByUser loads the invite's UsedByUser into the .R struct
func (os InviteSlice) LoadUsedByUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.UsedByUser(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {
			if !o.UsedBy.IsValue() {
				continue
			}

			if !(o.UsedBy.IsValue() && o.UsedBy.MustGet() == rel.ID) {
				continue
			}

			rel.R.UsedByInvites = append(rel.R.UsedByInvites, o)

			o.R.UsedByUser = rel
			break
		}
	}

	return nil
}

// LoadCreatedByUser loads the invite's CreatedByUser into the .R struct
func (o *Invite) LoadCreatedByUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.CreatedByUser = nil

	related, err := o.CreatedByUser(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.CreatedByInvites = InviteSlice{o}

	o.R.CreatedByUser = related
	return nil
}

// LoadCreatedByUser loads the invite's CreatedByUser into the .R struct
func (os InviteSlice) LoadCreatedByUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.CreatedByUser(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {
			if !o.CreatedBy.IsValue() {
				continue
			}

			if !(o.CreatedBy.IsValue() && o.CreatedBy.MustGet() == rel.ID) {
				continue
			}

			rel.R.CreatedByInvites = append(rel.R.CreatedByInvites, o)

			o.R.CreatedByUser = rel
			break
		}
	}

	return nil
}

type inviteJoins[Q dialect.Joinable] struct {
	typ           string
	UsedByUser    modAs[Q, userColumns]
	CreatedByUser modAs[Q, userColumns]
}

func (j inviteJoins[Q]) aliasedAs(alias string) inviteJoins[Q] {
	return buildInviteJoins[Q](buildInviteColumns(alias), j.typ)
}

func buildInviteJoins[Q dialect.Joinable](cols inviteColumns, typ string) inviteJoins[Q] {
	return inviteJoins[Q]{
		typ: typ,
		UsedByUser: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UsedBy),
					))
				}

				return mods
			},
		},
		CreatedByUser: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.CreatedBy),
					))
				}

				return mods
			},
		},
	}
}
