// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// User is an object representing the database table.
type User struct {
	ID           int64            `db:"id,pk" `
	Username     string           `db:"username" `
	PasswordHash string           `db:"password_hash" `
	Role         string           `db:"role" `
	FullName     null.Val[string] `db:"full_name" `
	Email        null.Val[string] `db:"email" `
	CreatedAt    time.Time        `db:"created_at" `
	UpdatedAt    time.Time        `db:"updated_at" `

	R userR `db:"-" `
}

// UserSlice is an alias for a slice of pointers to User.
// This should almost always be used instead of []*User.
type UserSlice []*User

// Users contains methods to work with the users table
var Users = sqlite.NewTablex[*User, UserSlice, *UserSetter]("", "users", buildUserColumns("users"))

// UsersQuery is a query on the users table
type UsersQuery = *sqlite.ViewQuery[*User, UserSlice]

// userR is where relationships are stored.
type userR struct {
	UsedByInvites    InviteSlice  // fk_invites_0
	CreatedByInvites InviteSlice  // fk_invites_1
	Sessions         SessionSlice // fk_sessions_0
}

func buildUserColumns(alias string) userColumns {
	return userColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "username", "password_hash", "role", "full_name", "email", "created_at", "updated_at",
		).WithParent("users"),
		tableAlias:   alias,
		ID:           sqlite.Quote(alias, "id"),
		Username:     sqlite.Quote(alias, "username"),
		PasswordHash: sqlite.Quote(alias, "password_hash"),
		Role:         sqlite.Quote(alias, "role"),
		FullName:     sqlite.Quote(alias, "full_name"),
		Email:        sqlite.Quote(alias, "email"),
		CreatedAt:    sqlite.Quote(alias, "created_at"),
		UpdatedAt:    sqlite.Quote(alias, "updated_at"),
	}
}

type userColumns struct {
	expr.ColumnsExpr
	tableAlias   string
	ID           sqlite.Expression
	Username     sqlite.Expression
	PasswordHash sqlite.Expression
	Role         sqlite.Expression
	FullName     sqlite.Expression
	Email        sqlite.Expression
	CreatedAt    sqlite.Expression
	UpdatedAt    sqlite.Expression
}

func (c userColumns) Alias() string {
	return c.tableAlias
}

func (userColumns) AliasedAs(alias string) userColumns {
	return buildUserColumns(alias)
}

// UserSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type UserSetter struct {
	ID           omit.Val[int64]      `db:"id,pk" `
	Username     omit.Val[string]     `db:"username" `
	PasswordHash omit.Val[string]     `db:"password_hash" `
	Role         omit.Val[string]     `db:"role" `
	FullName     omitnull.Val[string] `db:"full_name" `
	Email        omitnull.Val[string] `db:"email" `
	CreatedAt    omit.Val[time.Time]  `db:"created_at" `
	UpdatedAt    omit.Val[time.Time]  `db:"updated_at" `
}

func (s UserSetter) SetColumns() []string {
	vals := make([]string, 0, 8)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Username.IsValue() {
		vals = append(vals, "username")
	}
	if s.PasswordHash.IsValue() {
		vals = append(vals, "password_hash")
	}
	if s.Role.IsValue() {
		vals = append(vals, "role")
	}
	if !s.FullName.IsUnset() {
		vals = append(vals, "full_name")
	}
	if !s.Email.IsUnset() {
		vals = append(vals, "email")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s UserSetter) Overwrite(t *User) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Username.IsValue() {
		t.Username = s.Username.MustGet()
	}
	if s.PasswordHash.IsValue() {
		t.PasswordHash = s.PasswordHash.MustGet()
	}
	if s.Role.IsValue() {
		t.Role = s.Role.MustGet()
	}
	if !s.FullName.IsUnset() {
		t.FullName = s.FullName.MustGetNull()
	}
	if !s.Email.IsUnset() {
		t.Email = s.Email.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *UserSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Users.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"id"}
		}

	}

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 0, 8)
		if s.ID.IsValue() {
			vals = append(vals, sqlite.Arg(s.ID.MustGet()))
		}

		if s.Username.IsValue() {
			vals = append(vals, sqlite.Arg(s.Username.MustGet()))
		}

		if s.PasswordHash.IsValue() {
			vals = append(vals, sqlite.Arg(s.PasswordHash.MustGet()))
		}

		if s.Role.IsValue() {
			vals = append(vals, sqlite.Arg(s.Role.MustGet()))
		}

		if !s.FullName.IsUnset() {
			vals = append(vals, sqlite.Arg(s.FullName.MustGetNull()))
		}

		if !s.Email.IsUnset() {
			vals = append(vals, sqlite.Arg(s.Email.MustGetNull()))
		}

		if s.CreatedAt.IsValue() {
			vals = append(vals, sqlite.Arg(s.CreatedAt.MustGet()))
		}

		if s.UpdatedAt.IsValue() {
			vals = append(vals, sqlite.Arg(s.UpdatedAt.MustGet()))
		}

		if len(vals) == 0 {
			vals = append(vals, sqlite.Arg(nil))
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s UserSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s UserSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 8)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "id")...),
			sqlite.Arg(s.ID),
		}})
	}

	if s.Username.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "username")...),
			sqlite.Arg(s.Username),
		}})
	}

	if s.PasswordHash.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "password_hash")...),
			sqlite.Arg(s.PasswordHash),
		}})
	}

	if s.Role.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "role")...),
			sqlite.Arg(s.Role),
		}})
	}

	if !s.FullName.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "full_name")...),
			sqlite.Arg(s.FullName),
		}})
	}

	if !s.Email.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "email")...),
			sqlite.Arg(s.Email),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "created_at")...),
			sqlite.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "updated_at")...),
			sqlite.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindUser retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindUser(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*User, error) {
	if len(cols) == 0 {
		return Users.Query(
			sm.Where(Users.Columns.ID.EQ(sqlite.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Users.Query(
		sm.Where(Users.Columns.ID.EQ(sqlite.Arg(IDPK))),
		sm.Columns(Users.Columns.Only(cols...)),
	).One(ctx, exec)
}

// UserExists checks the presence of a single record by primary key
func UserExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return Users.Query(
		sm.Where(Users.Columns.ID.EQ(sqlite.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after User is retrieved from the database
func (o *User) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Users.AfterSelectHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Users.AfterInsertHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, UserSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the User
func (o *User) primaryKeyVals() bob.Expression {
	return sqlite.Arg(o.ID)
}

func (o *User) pkEQ() dialect.Expression {
	return sqlite.Quote("users", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the User
func (o *User) Update(ctx context.Context, exec bob.Executor, s *UserSetter) error {
	v, err := Users.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single User record with an executor
func (o *User) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Users.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the User using the executor
func (o *User) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Users.Query(
		sm.Where(Users.Columns.ID.EQ(sqlite.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after UserSlice is retrieved from the database
func (o UserSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Users.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Users.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o UserSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Quote("users", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o UserSlice) copyMatchingRows(from ...*User) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o UserSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Users.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *User:
				o.copyMatchingRows(retrieved)
			case []*User:
				o.copyMatchingRows(retrieved...)
			case UserSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a User or a slice of User
				// then run the AfterUpdateHooks on the slice
				_, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o UserSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Users.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *User:
				o.copyMatchingRows(retrieved)
			case []*User:
				o.copyMatchingRows(retrieved...)
			case UserSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a User or a slice of User
				// then run the AfterDeleteHooks on the slice
				_, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o UserSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals UserSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Users.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o UserSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Users.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o UserSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Users.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// UsedByInvites starts a query for related objects on invites
func (o *User) UsedByInvites(mods ...bob.Mod[*dialect.SelectQuery]) InvitesQuery {
	return Invites.Query(append(mods,
		sm.Where(Invites.Columns.UsedBy.EQ(sqlite.Arg(o.ID))),
	)...)
}

func (os UserSlice) UsedByInvites(mods ...bob.Mod[*dialect.SelectQuery]) InvitesQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.ID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return Invites.Query(append(mods,
		sm.Where(sqlite.Group(Invites.Columns.UsedBy).OP("IN", PKArgExpr)),
	)...)
}

// CreatedByInvites starts a query for related objects on invites
func (o *User) CreatedByInvites(mods ...bob.Mod[*dialect.SelectQuery]) InvitesQuery {
	return Invites.Query(append(mods,
		sm.Where(Invites.Columns.CreatedBy.EQ(sqlite.Arg(o.ID))),
	)...)
}

func (os UserSlice) CreatedByInvites(mods ...bob.Mod[*dialect.SelectQuery]) InvitesQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.ID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return Invites.Query(append(mods,
		sm.Where(sqlite.Group(Invites.Columns.CreatedBy).OP("IN", PKArgExpr)),
	)...)
}

// Sessions starts a query for related objects on sessions
func (o *User) Sessions(mods ...bob.Mod[*dialect.SelectQuery]) SessionsQuery {
	return Sessions.Query(append(mods,
		sm.Where(Sessions.Columns.UserID.EQ(sqlite.Arg(o.ID))),
	)...)
}

func (os UserSlice) Sessions(mods ...bob.Mod[*dialect.SelectQuery]) SessionsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.ID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return Sessions.Query(append(mods,
		sm.Where(sqlite.Group(Sessions.Columns.UserID).OP("IN", PKArgExpr)),
	)...)
}

func insertUserUsedByInvites0(ctx context.Context, exec bob.Executor, invites1 []*InviteSetter, user0 *User) (InviteSlice, error) {
	for i := range invites1 {
		invites1[i].UsedBy = omitnull.From(user0.ID)
	}

	ret, err := Invites.Insert(bob.ToMods(invites1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserUsedByInvites0: %w", err)
	}

	return ret, nil
}

func attachUserUsedByInvites0(ctx context.Context, exec bob.Executor, count int, invites1 InviteSlice, user0 *User) (InviteSlice, error) {
	setter := &InviteSetter{
		UsedBy: omitnull.From(user0.ID),
	}

	err := invites1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserUsedByInvites0: %w", err)
	}

	return invites1, nil
}

func (user0 *User) InsertUsedByInvites(ctx context.Context, exec bob.Executor, related ...*InviteSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	invites1, err := insertUserUsedByInvites0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.UsedByInvites = append(user0.R.UsedByInvites, invites1...)

	for _, rel := range invites1 {
		rel.R.UsedByUser = user0
	}
	return nil
}

func (user0 *User) AttachUsedByInvites(ctx context.Context, exec bob.Executor, related ...*Invite) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	invites1 := InviteSlice(related)

	_, err = attachUserUsedByInvites0(ctx, exec, len(related), invites1, user0)
	if err != nil {
		return err
	}

	user0.R.UsedByInvites = append(user0.R.UsedByInvites, invites1...)

	for _, rel := range related {
		rel.R.UsedByUser = user0
	}

	return nil
}

func insertUserCreatedByInvites0(ctx context.Context, exec bob.Executor, invites1 []*InviteSetter, user0 *User) (InviteSlice, error) {
	for i := range invites1 {
		invites1[i].CreatedBy = omit.From(user0.ID)
	}

	ret, err := Invites.Insert(bob.ToMods(invites1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserCreatedByInvites0: %w", err)
	}

	return ret, nil
}

func attachUserCreatedByInvites0(ctx context.Context, exec bob.Executor, count int, invites1 InviteSlice, user0 *User) (InviteSlice, error) {
	setter := &InviteSetter{
		CreatedBy: omit.From(user0.ID),
	}

	err := invites1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserCreatedByInvites0: %w", err)
	}

	return invites1, nil
}

func (user0 *User) InsertCreatedByInvites(ctx context.Context, exec bob.Executor, related ...*InviteSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	invites1, err := insertUserCreatedByInvites0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.CreatedByInvites = append(user0.R.CreatedByInvites, invites1...)

	for _, rel := range invites1 {
		rel.R.CreatedByUser = user0
	}
	return nil
}

func (user0 *User) AttachCreatedByInvites(ctx context.Context, exec bob.Executor, related ...*Invite) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	invites1 := InviteSlice(related)

	_, err = attachUserCreatedByInvites0(ctx, exec, len(related), invites1, user0)
	if err != nil {
		return err
	}

	user0.R.CreatedByInvites = append(user0.R.CreatedByInvites, invites1...)

	for _, rel := range related {
		rel.R.CreatedByUser = user0
	}

	return nil
}

func insertUserSessions0(ctx context.Context, exec bob.Executor, sessions1 []*SessionSetter, user0 *User) (SessionSlice, error) {
	for i := range sessions1 {
		sessions1[i].UserID = omit.From(user0.ID)
	}

	ret, err := Sessions.Insert(bob.ToMods(sessions1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserSessions0: %w", err)
	}

	return ret, nil
}

func attachUserSessions0(ctx context.Context, exec bob.Executor, count int, sessions1 SessionSlice, user0 *User) (SessionSlice, error) {
	setter := &SessionSetter{
		UserID: omit.From(user0.ID),
	}

	err := sessions1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserSessions0: %w", err)
	}

	return sessions1, nil
}

func (user0 *User) InsertSessions(ctx context.Context, exec bob.Executor, related ...*SessionSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	sessions1, err := insertUserSessions0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.Sessions = append(user0.R.Sessions, sessions1...)

	for _, rel := range sessions1 {
		rel.R.User = user0
	}
	return nil
}

func (user0 *User) AttachSessions(ctx context.Context, exec bob.Executor, related ...*Session) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	sessions1 := SessionSlice(related)

	_, err = attachUserSessions0(ctx, exec, len(related), sessions1, user0)
	if err != nil {
		return err
	}

	user0.R.Sessions = append(user0.R.Sessions, sessions1...)

	for _, rel := range related {
		rel.R.User = user0
	}

	return nil
}

type userWhere[Q sqlite.Filterable] struct {
	ID           sqlite.WhereMod[Q, int64]
	Username     sqlite.WhereMod[Q, string]
	PasswordHash sqlite.WhereMod[Q, string]
	Role         sqlite.WhereMod[Q, string]
	FullName     sqlite.WhereNullMod[Q, string]
	Email        sqlite.WhereNullMod[Q, string]
	CreatedAt    sqlite.WhereMod[Q, time.Time]
	UpdatedAt    sqlite.WhereMod[Q, time.Time]
}

func (userWhere[Q]) AliasedAs(alias string) userWhere[Q] {
	return buildUserWhere[Q](buildUserColumns(alias))
}

func buildUserWhere[Q sqlite.Filterable](cols userColumns) userWhere[Q] {
	return userWhere[Q]{
		ID:           sqlite.Where[Q, int64](cols.ID),
		Username:     sqlite.Where[Q, string](cols.Username),
		PasswordHash: sqlite.Where[Q, string](cols.PasswordHash),
		Role:         sqlite.Where[Q, string](cols.Role),
		FullName:     sqlite.WhereNull[Q, string](cols.FullName),
		Email:        sqlite.WhereNull[Q, string](cols.Email),
		CreatedAt:    sqlite.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:    sqlite.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *User) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "UsedByInvites":
		rels, ok := retrieved.(InviteSlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.UsedByInvites = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.UsedByUser = o
			}
		}
		return nil
	case "CreatedByInvites":
		rels, ok := retrieved.(InviteSlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.CreatedByInvites = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.CreatedByUser = o
			}
		}
		return nil
	case "Sessions":
		rels, ok := retrieved.(SessionSlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.Sessions = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.User = o
			}
		}
		return nil
	default:
		return fmt.Errorf("user has no relationship %q", name)
	}
}

type userPreloader struct{}

func buildUserPreloader() userPreloader {
	return userPreloader{}
}

type userThenLoader[Q orm.Loadable] struct {
	UsedByInvites    func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	CreatedByInvites func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Sessions         func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildUserThenLoader[Q orm.Loadable]() userThenLoader[Q] {
	type UsedByInvitesLoadInterface interface {
		LoadUsedByInvites(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type CreatedByInvitesLoadInterface interface {
		LoadCreatedByInvites(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type SessionsLoadInterface interface {
		LoadSessions(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return userThenLoader[Q]{
		UsedByInvites: thenLoadBuilder[Q](
			"UsedByInvites",
			func(ctx context.Context, exec bob.Executor, retrieved UsedByInvitesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUsedByInvites(ctx, exec, mods...)
			},
		),
		CreatedByInvites: thenLoadBuilder[Q](
			"CreatedByInvites",
			func(ctx context.Context, exec bob.Executor, retrieved CreatedByInvitesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCreatedByInvites(ctx, exec, mods...)
			},
		),
		Sessions: thenLoadBuilder[Q](
			"Sessions",
			func(ctx context.Context, exec bob.Executor, retrieved SessionsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadSessions(ctx, exec, mods...)
			},
		),
	}
}

// LoadUsedByInvites loads the user's UsedByInvites into the .R struct
func (o *User) LoadUsedByInvites(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.UsedByInvites = nil

	related, err := o.UsedByInvites(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.UsedByUser = o
	}

	o.R.UsedByInvites = related
	return nil
}

// LoadUsedByInvites loads the user's UsedByInvites into the .R struct
func (os UserSlice) LoadUsedByInvites(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	invites, err := os.UsedByInvites(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.UsedByInvites = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range invites {

			if !rel.UsedBy.IsValue() {
				continue
			}
			if !(rel.UsedBy.IsValue() && o.ID == rel.UsedBy.MustGet()) {
				continue
			}

			rel.R.UsedByUser = o

			o.R.UsedByInvites = append(o.R.UsedByInvites, rel)
		}
	}

	return nil
}

// LoadCreatedByInvites loads the user's CreatedByInvites into the .R struct
func (o *User) LoadCreatedByInvites(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.CreatedByInvites = nil

	related, err := o.CreatedByInvites(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.CreatedByUser = o
	}

	o.R.CreatedByInvites = related
	return nil
}

// LoadCreatedByInvites loads the user's CreatedByInvites into the .R struct
func (os UserSlice) LoadCreatedByInvites(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	invites, err := os.CreatedByInvites(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.CreatedByInvites = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range invites {

			if !(o.ID == rel.CreatedBy) {
				continue
			}

			rel.R.CreatedByUser = o

			o.R.CreatedByInvites = append(o.R.CreatedByInvites, rel)
		}
	}

	return nil
}

// LoadSessions loads the user's Sessions into the .R struct
func (o *User) LoadSessions(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Sessions = nil

	related, err := o.Sessions(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.User = o
	}

	o.R.Sessions = related
	return nil
}

// LoadSessions loads the user's Sessions into the .R struct
func (os UserSlice) LoadSessions(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	sessions, err := os.Sessions(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Sessions = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range sessions {

			if !(o.ID == rel.UserID) {
				continue
			}

			rel.R.User = o

			o.R.Sessions = append(o.R.Sessions, rel)
		}
	}

	return nil
}

type userJoins[Q dialect.Joinable] struct {
	typ              string
	UsedByInvites    modAs[Q, inviteColumns]
	CreatedByInvites modAs[Q, inviteColumns]
	Sessions         modAs[Q, sessionColumns]
}

func (j userJoins[Q]) aliasedAs(alias string) userJoins[Q] {
	return buildUserJoins[Q](buildUserColumns(alias), j.typ)
}

func buildUserJoins[Q dialect.Joinable](cols userColumns, typ string) userJoins[Q] {
	return userJoins[Q]{
		typ: typ,
		UsedByInvites: modAs[Q, inviteColumns]{
			c: Invites.Columns,
			f: func(to inviteColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Invites.Name().As(to.Alias())).On(
						to.UsedBy.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		CreatedByInvites: modAs[Q, inviteColumns]{
			c: Invites.Columns,
			f: func(to inviteColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Invites.Name().As(to.Alias())).On(
						to.CreatedBy.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Sessions: modAs[Q, sessionColumns]{
			c: Sessions.Columns,
			f: func(to sessionColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Sessions.Name().As(to.Alias())).On(
						to.UserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
