// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var InviteErrors = &inviteErrors{
	ErrUniquePkMainInvites: &UniqueConstraintError{
		schema:  "",
		table:   "invites",
		columns: []string{"id"},
		s:       "pk_main_invites",
	},

	ErrUniqueSqliteAutoindexInvites1: &UniqueConstraintError{
		schema:  "",
		table:   "invites",
		columns: []string{"code"},
		s:       "sqlite_autoindex_invites_1",
	},
}

type inviteErrors struct {
	ErrUniquePkMainInvites *UniqueConstraintError

	ErrUniqueSqliteAutoindexInvites1 *UniqueConstraintError
}
