// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var SessionErrors = &sessionErrors{
	ErrUniquePkMainSessions: &UniqueConstraintError{
		schema:  "",
		table:   "sessions",
		columns: []string{"id"},
		s:       "pk_main_sessions",
	},

	ErrUniqueSqliteAutoindexSessions1: &UniqueConstraintError{
		schema:  "",
		table:   "sessions",
		columns: []string{"token"},
		s:       "sqlite_autoindex_sessions_1",
	},
}

type sessionErrors struct {
	ErrUniquePkMainSessions *UniqueConstraintError

	ErrUniqueSqliteAutoindexSessions1 *UniqueConstraintError
}
