// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import "context"

type contextKey string

var (
	// Relationship Contexts for invites
	inviteWithParentsCascadingCtx = newContextual[bool]("inviteWithParentsCascading")
	inviteRelUsedByUserCtx        = newContextual[bool]("invites.users.fk_invites_0")
	inviteRelCreatedByUserCtx     = newContextual[bool]("invites.users.fk_invites_1")

	// Relationship Contexts for sessions
	sessionWithParentsCascadingCtx = newContextual[bool]("sessionWithParentsCascading")
	sessionRelUserCtx              = newContextual[bool]("sessions.users.fk_sessions_0")

	// Relationship Contexts for users
	userWithParentsCascadingCtx = newContextual[bool]("userWithParentsCascading")
	userRelUsedByInvitesCtx     = newContextual[bool]("invites.users.fk_invites_0")
	userRelCreatedByInvitesCtx  = newContextual[bool]("invites.users.fk_invites_1")
	userRelSessionsCtx          = newContextual[bool]("sessions.users.fk_sessions_0")
)

// Contextual is a convienience wrapper around context.WithValue and context.Value
type contextual[V any] struct {
	key contextKey
}

func newContextual[V any](key string) contextual[V] {
	return contextual[V]{key: contextKey(key)}
}

func (k contextual[V]) WithValue(ctx context.Context, val V) context.Context {
	return context.WithValue(ctx, k.key, val)
}

func (k contextual[V]) Value(ctx context.Context) (V, bool) {
	v, ok := ctx.Value(k.key).(V)
	return v, ok
}
