// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"time"

	"github.com/aarondl/opt/null"
	models "github.com/h1divp/yippee/internal/models"
)

type Factory struct {
	baseSessionMods SessionModSlice
	baseUserMods    UserModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewSession(mods ...SessionMod) *SessionTemplate {
	return f.NewSessionWithContext(context.Background(), mods...)
}

func (f *Factory) NewSessionWithContext(ctx context.Context, mods ...SessionMod) *SessionTemplate {
	o := &SessionTemplate{f: f}

	if f != nil {
		f.baseSessionMods.Apply(ctx, o)
	}

	SessionModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingSession(m *models.Session) *SessionTemplate {
	o := &SessionTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.Token = func() string { return m.Token }
	o.UserID = func() int64 { return m.UserID }
	o.ExpiresAt = func() time.Time { return m.ExpiresAt }
	o.CreatedAt = func() time.Time { return m.CreatedAt }

	ctx := context.Background()
	if m.R.User != nil {
		SessionMods.WithExistingUser(m.R.User).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewUser(mods ...UserMod) *UserTemplate {
	return f.NewUserWithContext(context.Background(), mods...)
}

func (f *Factory) NewUserWithContext(ctx context.Context, mods ...UserMod) *UserTemplate {
	o := &UserTemplate{f: f}

	if f != nil {
		f.baseUserMods.Apply(ctx, o)
	}

	UserModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingUser(m *models.User) *UserTemplate {
	o := &UserTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.Username = func() string { return m.Username }
	o.PasswordHash = func() string { return m.PasswordHash }
	o.Role = func() string { return m.Role }
	o.FullName = func() null.Val[string] { return m.FullName }
	o.Email = func() null.Val[string] { return m.Email }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.UpdatedAt = func() time.Time { return m.UpdatedAt }

	ctx := context.Background()
	if len(m.R.Sessions) > 0 {
		UserMods.AddExistingSessions(m.R.Sessions...).Apply(ctx, o)
	}

	return o
}

func (f *Factory) ClearBaseSessionMods() {
	f.baseSessionMods = nil
}

func (f *Factory) AddBaseSessionMod(mods ...SessionMod) {
	f.baseSessionMods = append(f.baseSessionMods, mods...)
}

func (f *Factory) ClearBaseUserMods() {
	f.baseUserMods = nil
}

func (f *Factory) AddBaseUserMod(mods ...UserMod) {
	f.baseUserMods = append(f.baseUserMods, mods...)
}
