// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	models "github.com/h1divp/yippee/internal/models"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type InviteMod interface {
	Apply(context.Context, *InviteTemplate)
}

type InviteModFunc func(context.Context, *InviteTemplate)

func (f InviteModFunc) Apply(ctx context.Context, n *InviteTemplate) {
	f(ctx, n)
}

type InviteModSlice []InviteMod

func (mods InviteModSlice) Apply(ctx context.Context, n *InviteTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// InviteTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type InviteTemplate struct {
	ID        func() int64
	Code      func() string
	CreatedBy func() int64
	UsedBy    func() null.Val[int64]
	UsedAt    func() null.Val[time.Time]
	ExpiresAt func() null.Val[time.Time]
	CreatedAt func() time.Time

	r inviteR
	f *Factory

	alreadyPersisted bool
}

type inviteR struct {
	UsedByUser    *inviteRUsedByUserR
	CreatedByUser *inviteRCreatedByUserR
}

type inviteRUsedByUserR struct {
	o *UserTemplate
}
type inviteRCreatedByUserR struct {
	o *UserTemplate
}

// Apply mods to the InviteTemplate
func (o *InviteTemplate) Apply(ctx context.Context, mods ...InviteMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Invite
// according to the relationships in the template. Nothing is inserted into the db
func (t InviteTemplate) setModelRels(o *models.Invite) {
	if t.r.UsedByUser != nil {
		rel := t.r.UsedByUser.o.Build()
		rel.R.UsedByInvites = append(rel.R.UsedByInvites, o)
		o.UsedBy = null.From(rel.ID) // h2
		o.R.UsedByUser = rel
	}

	if t.r.CreatedByUser != nil {
		rel := t.r.CreatedByUser.o.Build()
		rel.R.CreatedByInvites = append(rel.R.CreatedByInvites, o)
		o.CreatedBy = rel.ID // h2
		o.R.CreatedByUser = rel
	}
}

// BuildSetter returns an *models.InviteSetter
// this does nothing with the relationship templates
func (o InviteTemplate) BuildSetter() *models.InviteSetter {
	m := &models.InviteSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Code != nil {
		val := o.Code()
		m.Code = omit.From(val)
	}
	if o.CreatedBy != nil {
		val := o.CreatedBy()
		m.CreatedBy = omit.From(val)
	}
	if o.UsedBy != nil {
		val := o.UsedBy()
		m.UsedBy = omitnull.FromNull(val)
	}
	if o.UsedAt != nil {
		val := o.UsedAt()
		m.UsedAt = omitnull.FromNull(val)
	}
	if o.ExpiresAt != nil {
		val := o.ExpiresAt()
		m.ExpiresAt = omitnull.FromNull(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.InviteSetter
// this does nothing with the relationship templates
func (o InviteTemplate) BuildManySetter(number int) []*models.InviteSetter {
	m := make([]*models.InviteSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Invite
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use InviteTemplate.Create
func (o InviteTemplate) Build() *models.Invite {
	m := &models.Invite{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Code != nil {
		m.Code = o.Code()
	}
	if o.CreatedBy != nil {
		m.CreatedBy = o.CreatedBy()
	}
	if o.UsedBy != nil {
		m.UsedBy = o.UsedBy()
	}
	if o.UsedAt != nil {
		m.UsedAt = o.UsedAt()
	}
	if o.ExpiresAt != nil {
		m.ExpiresAt = o.ExpiresAt()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.InviteSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use InviteTemplate.CreateMany
func (o InviteTemplate) BuildMany(number int) models.InviteSlice {
	m := make(models.InviteSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableInvite(m *models.InviteSetter) {
	if !(m.Code.IsValue()) {
		val := random_string(nil)
		m.Code = omit.From(val)
	}
	if !(m.CreatedBy.IsValue()) {
		val := random_int64(nil)
		m.CreatedBy = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Invite
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *InviteTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Invite) error {
	var err error

	isUsedByUserDone, _ := inviteRelUsedByUserCtx.Value(ctx)
	if !isUsedByUserDone && o.r.UsedByUser != nil {
		ctx = inviteRelUsedByUserCtx.WithValue(ctx, true)
		if o.r.UsedByUser.o.alreadyPersisted {
			m.R.UsedByUser = o.r.UsedByUser.o.Build()
		} else {
			var rel0 *models.User
			rel0, err = o.r.UsedByUser.o.Create(ctx, exec)
			if err != nil {
				return err
			}
			err = m.AttachUsedByUser(ctx, exec, rel0)
			if err != nil {
				return err
			}
		}

	}

	return err
}

// Create builds a invite and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *InviteTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Invite, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableInvite(opt)

	if o.r.CreatedByUser == nil {
		InviteMods.WithNewCreatedByUser().Apply(ctx, o)
	}

	var rel1 *models.User

	if o.r.CreatedByUser.o.alreadyPersisted {
		rel1 = o.r.CreatedByUser.o.Build()
	} else {
		rel1, err = o.r.CreatedByUser.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.CreatedBy = omit.From(rel1.ID)

	m, err := models.Invites.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.CreatedByUser = rel1

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a invite and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *InviteTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Invite {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a invite and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *InviteTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Invite {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple invites and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o InviteTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.InviteSlice, error) {
	var err error
	m := make(models.InviteSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple invites and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o InviteTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.InviteSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple invites and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o InviteTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.InviteSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Invite has methods that act as mods for the InviteTemplate
var InviteMods inviteMods

type inviteMods struct{}

func (m inviteMods) RandomizeAllColumns(f *faker.Faker) InviteMod {
	return InviteModSlice{
		InviteMods.RandomID(f),
		InviteMods.RandomCode(f),
		InviteMods.RandomCreatedBy(f),
		InviteMods.RandomUsedBy(f),
		InviteMods.RandomUsedAt(f),
		InviteMods.RandomExpiresAt(f),
		InviteMods.RandomCreatedAt(f),
	}
}

// Set the model columns to this value
func (m inviteMods) ID(val int64) InviteMod {
	return InviteModFunc(func(_ context.Context, o *InviteTemplate) {
		o.ID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m inviteMods) IDFunc(f func() int64) InviteMod {
	return InviteModFunc(func(_ context.Context, o *InviteTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m inviteMods) UnsetID() InviteMod {
	return InviteModFunc(func(_ context.Context, o *InviteTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m inviteMods) RandomID(f *faker.Faker) InviteMod {
	return InviteModFunc(func(_ context.Context, o *InviteTemplate) {
		o.ID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m inviteMods) Code(val string) InviteMod {
	return InviteModFunc(func(_ context.Context, o *InviteTemplate) {
		o.Code = func() string { return val }
	})
}

// Set the Column from the function
func (m inviteMods) CodeFunc(f func() string) InviteMod {
	return InviteModFunc(func(_ context.Context, o *InviteTemplate) {
		o.Code = f
	})
}

// Clear any values for the column
func (m inviteMods) UnsetCode() InviteMod {
	return InviteModFunc(func(_ context.Context, o *InviteTemplate) {
		o.Code = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m inviteMods) RandomCode(f *faker.Faker) InviteMod {
	return InviteModFunc(func(_ context.Context, o *InviteTemplate) {
		o.Code = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m inviteMods) CreatedBy(val int64) InviteMod {
	return InviteModFunc(func(_ context.Context, o *InviteTemplate) {
		o.CreatedBy = func() int64 { return val }
	})
}

// Set the Column from the function
func (m inviteMods) CreatedByFunc(f func() int64) InviteMod {
	return InviteModFunc(func(_ context.Context, o *InviteTemplate) {
		o.CreatedBy = f
	})
}

// Clear any values for the column
func (m inviteMods) UnsetCreatedBy() InviteMod {
	return InviteModFunc(func(_ context.Context, o *InviteTemplate) {
		o.CreatedBy = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m inviteMods) RandomCreatedBy(f *faker.Faker) InviteMod {
	return InviteModFunc(func(_ context.Context, o *InviteTemplate) {
		o.CreatedBy = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m inviteMods) UsedBy(val null.Val[int64]) InviteMod {
	return InviteModFunc(func(_ context.Context, o *InviteTemplate) {
		o.UsedBy = func() null.Val[int64] { return val }
	})
}

// Set the Column from the function
func (m inviteMods) UsedByFunc(f func() null.Val[int64]) InviteMod {
	return InviteModFunc(func(_ context.Context, o *InviteTemplate) {
		o.UsedBy = f
	})
}

// Clear any values for the column
func (m inviteMods) UnsetUsedBy() InviteMod {
	return InviteModFunc(func(_ context.Context, o *InviteTemplate) {
		o.UsedBy = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m inviteMods) RandomUsedBy(f *faker.Faker) InviteMod {
	return InviteModFunc(func(_ context.Context, o *InviteTemplate) {
		o.UsedBy = func() null.Val[int64] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int64(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m inviteMods) RandomUsedByNotNull(f *faker.Faker) InviteMod {
	return InviteModFunc(func(_ context.Context, o *InviteTemplate) {
		o.UsedBy = func() null.Val[int64] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int64(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m inviteMods) UsedAt(val null.Val[time.Time]) InviteMod {
	return InviteModFunc(func(_ context.Context, o *InviteTemplate) {
		o.UsedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m inviteMods) UsedAtFunc(f func() null.Val[time.Time]) InviteMod {
	return InviteModFunc(func(_ context.Context, o *InviteTemplate) {
		o.UsedAt = f
	})
}

// Clear any values for the column
func (m inviteMods) UnsetUsedAt() InviteMod {
	return InviteModFunc(func(_ context.Context, o *InviteTemplate) {
		o.UsedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m inviteMods) RandomUsedAt(f *faker.Faker) InviteMod {
	return InviteModFunc(func(_ context.Context, o *InviteTemplate) {
		o.UsedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m inviteMods) RandomUsedAtNotNull(f *faker.Faker) InviteMod {
	return InviteModFunc(func(_ context.Context, o *InviteTemplate) {
		o.UsedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m inviteMods) ExpiresAt(val null.Val[time.Time]) InviteMod {
	return InviteModFunc(func(_ context.Context, o *InviteTemplate) {
		o.ExpiresAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m inviteMods) ExpiresAtFunc(f func() null.Val[time.Time]) InviteMod {
	return InviteModFunc(func(_ context.Context, o *InviteTemplate) {
		o.ExpiresAt = f
	})
}

// Clear any values for the column
func (m inviteMods) UnsetExpiresAt() InviteMod {
	return InviteModFunc(func(_ context.Context, o *InviteTemplate) {
		o.ExpiresAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m inviteMods) RandomExpiresAt(f *faker.Faker) InviteMod {
	return InviteModFunc(func(_ context.Context, o *InviteTemplate) {
		o.ExpiresAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m inviteMods) RandomExpiresAtNotNull(f *faker.Faker) InviteMod {
	return InviteModFunc(func(_ context.Context, o *InviteTemplate) {
		o.ExpiresAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m inviteMods) CreatedAt(val time.Time) InviteMod {
	return InviteModFunc(func(_ context.Context, o *InviteTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m inviteMods) CreatedAtFunc(f func() time.Time) InviteMod {
	return InviteModFunc(func(_ context.Context, o *InviteTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m inviteMods) UnsetCreatedAt() InviteMod {
	return InviteModFunc(func(_ context.Context, o *InviteTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m inviteMods) RandomCreatedAt(f *faker.Faker) InviteMod {
	return InviteModFunc(func(_ context.Context, o *InviteTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m inviteMods) WithParentsCascading() InviteMod {
	return InviteModFunc(func(ctx context.Context, o *InviteTemplate) {
		if isDone, _ := inviteWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = inviteWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewUserWithContext(ctx, UserMods.WithParentsCascading())
			m.WithUsedByUser(related).Apply(ctx, o)
		}
		{

			related := o.f.NewUserWithContext(ctx, UserMods.WithParentsCascading())
			m.WithCreatedByUser(related).Apply(ctx, o)
		}
	})
}

func (m inviteMods) WithUsedByUser(rel *UserTemplate) InviteMod {
	return InviteModFunc(func(ctx context.Context, o *InviteTemplate) {
		o.r.UsedByUser = &inviteRUsedByUserR{
			o: rel,
		}
	})
}

func (m inviteMods) WithNewUsedByUser(mods ...UserMod) InviteMod {
	return InviteModFunc(func(ctx context.Context, o *InviteTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)

		m.WithUsedByUser(related).Apply(ctx, o)
	})
}

func (m inviteMods) WithExistingUsedByUser(em *models.User) InviteMod {
	return InviteModFunc(func(ctx context.Context, o *InviteTemplate) {
		o.r.UsedByUser = &inviteRUsedByUserR{
			o: o.f.FromExistingUser(em),
		}
	})
}

func (m inviteMods) WithoutUsedByUser() InviteMod {
	return InviteModFunc(func(ctx context.Context, o *InviteTemplate) {
		o.r.UsedByUser = nil
	})
}

func (m inviteMods) WithCreatedByUser(rel *UserTemplate) InviteMod {
	return InviteModFunc(func(ctx context.Context, o *InviteTemplate) {
		o.r.CreatedByUser = &inviteRCreatedByUserR{
			o: rel,
		}
	})
}

func (m inviteMods) WithNewCreatedByUser(mods ...UserMod) InviteMod {
	return InviteModFunc(func(ctx context.Context, o *InviteTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)

		m.WithCreatedByUser(related).Apply(ctx, o)
	})
}

func (m inviteMods) WithExistingCreatedByUser(em *models.User) InviteMod {
	return InviteModFunc(func(ctx context.Context, o *InviteTemplate) {
		o.r.CreatedByUser = &inviteRCreatedByUserR{
			o: o.f.FromExistingUser(em),
		}
	})
}

func (m inviteMods) WithoutCreatedByUser() InviteMod {
	return InviteModFunc(func(ctx context.Context, o *InviteTemplate) {
		o.r.CreatedByUser = nil
	})
}
